### ISSUE TITLE
mangling of CSS variables (custom properties)?

### ISSUE THREAD

**Issue by tameraydin** [sndyuk/mangle-css-class-webpack-plugin#51]
Hi, thanks for this project!

Although the focus of plugin's is clearly class-names only, it would be nice if it also mangles CSS variables (custom properties) optionally.

```css
:root {
  --l-long-variable-names: 1px;
}
... {
  padding: var(--l-long-variable-names)
}
```
->
```css
:root {
  --a: 1px;
}
... {
  padding: var(--a)
}
```

Practically below change will enable it:

```diff
-    classnameRegex = new RegExp(`\\\.(${opts.classNameRegExp})`, 'g');
+    classnameRegex = new RegExp(`\(?:\.?|--)(${opts.classNameRegExp})`, 'g');
```

If you are willing to introduce this, happy to create a PR with tests.
